### ISSUE TITLE
Methods that return nothing must contain `result` field

### ISSUE THREAD

**Issue by oblique** [filecoin-project/go-jsonrpc#102]
We were trying to call a method that returns nothing but the library that we use  in the client rejects to deserialize the response.

After some investigation we found the following in [JSON RPC 2.0 spec](https://www.jsonrpc.org/specification#response_object):

> **result**
>   This member is REQUIRED on success.
>   This member MUST NOT exist if there was an error invoking the method.
>   The value of this member is determined by the method invoked on the Server.
>
> **error**
>   This member is REQUIRED on error.
>   This member MUST NOT exist if there was no error triggered during invocation.
>   The value for this member MUST be an Object as defined in section 5.1.

So on success the `result` field must exists.

The following unit tests are wrong:
https://github.com/filecoin-project/go-jsonrpc/blob/17a35772b24f59ceee25cc8d8177a2b255a659ac/rpc_test.go#L130-L133

**Comment by oblique** [comment]
This is what other servers return on a successful call:

```json
{
    "jsonrpc": "2.0",
    "result": null,
    "id": 1
}
```

**Comment by Wondertan** [comment]
@oblique, so to make this spec compliant, we would change unit tests to return `"result": null,` in the expected response, correct?

**Comment by zvolin** [comment]
yes
