### ISSUE TITLE
Support for sending lowercase method names by the client

### ISSUE THREAD

**Issue by Lukasz032** [filecoin-project/go-jsonrpc#105]
For now, the client sends the exact method name as the function in a `struct` it's bound to. For better compatibility with other server implementations, it'd be nice to be able to send method names in `lowercase` and `camelCase` instead of just `PascalCase`. It can be a configurable option to set during client creation (since in Golang it's necessary to have exportable functions `PascalCase`d regardless of what the server actually expects).

**Comment by magik6k** [comment]
This is possible to achieve with Aliases, see e.g.

https://github.com/filecoin-project/go-jsonrpc/blob/2cfe810e5d2f2795f12f52c1dd334dbe52b01055/rpc_test.go#L1284-L1291
