### ISSUE TITLE
Restore CI

### ISSUE THREAD

**Issue by rvagg** [filecoin-project/go-jsonrpc#109]
CircleCI isn't running here anymore. Investigate how painful it would be to switch to plain web3-bot unified CI.

**Comment by rvagg** [comment]
It seems that CI is running here again. But I've introduced #110 to convert to GHA anyway, it'll also need `@web3-bot` added to the users here to keep it updated.

**Comment by rjan90** [comment]
Closing this ticket as the circleci webhook has been removed, and we have converted to GHA.
