### ISSUE TITLE
How can i get a rpc error return when define a chan response in rpc call?

### ISSUE THREAD

**Issue by IPFS-grandhelmsman** [filecoin-project/go-jsonrpc#14]
I found that when it define a chan rpc api, it can't receive the rpc server error when the client called.

api:
```
WorkerQueue(context.Context, ffiwrapper.WorkerCfg) (<-chan ffiwrapper.WorkerTask, error)
```

rpc server implement the errors.
```
func (sb *Sealer) AddWorker(ctx context.Context, cfg WorkerCfg) (<-chan WorkerTask, error) {
    _remoteLk.Lock()
    defer _remoteLk.Unlock()
    if len(cfg.ID) == 0 { 
        return nil, errors.New("Worker ID not found").As(cfg)
    }   
    if old, ok := _remotes[cfg.ID]; ok {
        return nil, errors.New("The worker has exist").As(old.cfg)
    } 
    ...
}
```

rpc client should expect a error return, but nothing.

maybe cause here:
https://github.com/filecoin-project/go-jsonrpc/blob/master/handler.go#L228
and here:
https://github.com/filecoin-project/go-jsonrpc/blob/master/handler.go#L252

![image](https://user-images.githubusercontent.com/53922818/87848008-f841ac00-c90e-11ea-925a-bfe8f6337a16.png)

**Comment by magik6k** [comment]
Fix merged in #16
