### ISSUE TITLE
websocket error {"error": "websocket: close 1000 (normal)"}

### ISSUE THREAD

**Issue by xcshuan** [filecoin-project/go-jsonrpc#57]
when client call a rpc call, the server print 
> go-jsonrpc@v0.1.3/websocket.go:624      websocket error {"error": "websocket: close 1000 (normal)"}

**Comment by magik6k** [comment]
This should become significantly better with https://github.com/filecoin-project/go-jsonrpc/pull/97 (in go-jsonrpc v0.2.2).

Feel free to reopen, ideally with some more logs, if still not fixed
